# Generated by Django 4.2.1 on 2023-05-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('binance', 'Binance'), ('kucoin', 'KuCoin')], max_length=50)),
                ('website', models.URLField()),
                ('api_key', models.CharField(default='YOUR_API_KEY', max_length=100)),
                ('api_secret', models.CharField(default='YOUR_API_SECRET', max_length=100)),
                ('api_passphrase', models.CharField(default='YOUR_API_PASSPHRASE', max_length=100)),
                ('sell_percentage', models.FloatField(default=0.5)),
                ('buy_percentage', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
