# Generated by Django 4.2.1 on 2023-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('binance', 'Binance'), ('kucoin', 'KuCoin')], max_length=50, unique=True),
        ),
    ]
