# Generated by Django 4.2.1 on 2023-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_exchange_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('binance', 'Binance'), ('kucoin', 'KuCoin'), ('huobi', 'Huobi')], max_length=50, unique=True),
        ),
    ]
