# Generated by Django 4.2.1 on 2023-05-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_coin', models.CharField(max_length=50)),
                ('quote_coin', models.CharField(max_length=50)),
                ('supported_exchanges', models.ManyToManyField(to='exchanges.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('order_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=4)),
                ('coins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coinpair')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
            ],
        ),
    ]
