# Generated by Django 4.2.1 on 2023-05-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_coins_order_coin_pair_order_quantity_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('ask', 'Ask'), ('bid', 'Bid')], max_length=4),
        ),
    ]
