# Generated by Django 4.2.1 on 2023-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpair',
            name='sell_net',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
